export interface House {
    url:string
    name:string
    region:string
    coatOfArms:string
    word:string
    titles:string[]
    seats:string[]
    currenctLord:string
    heir:string
    overlord:string
    overlordName:string
    founded:string
    founder:string
    diedOut:string
    ancestralWeapons:string[]
    cadetBranches:string[]
    swornMembers:string[]
}